#!/usr/bin/env bash

cd ~/repos/pihole/

scp -i ~/.ssh/id_ed25519 -r compulim@dns1.localdomain:/home/compulim/repos/pihole/etc/cloudflared/ ~/repos/pihole/etc/cloudflared/
scp -i ~/.ssh/id_ed25519 -r compulim@dns1.localdomain:/home/compulim/repos/pihole/etc/dnsmasq.d/ ~/repos/pihole/etc/dnsmasq.d/
rsync \
  -e "ssh -i ~/.ssh/id_ed25519" \
  -av \
  --progress \
  --exclude='config_backups/' \
  --exclude='corrupted/' \
  --exclude='logrotate' \
  compulim@dns1.localdomain: /repos/pihole/etc/pihole/ \
  ~/repos/pihole/etc/pihole/

# docker compose exec pihole pihole restartdns
docker compose restart pihole
